OnlineshoppingStore.WebUI/Models/CartIndexViewModel.cs
using OnlineShoppingStore.Domain.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace OnlineshoppingStore.WebUI.Models
{
    public class CartIndexViewModel
    {
        public Cart Cart { get; set; }
        public string ReturnUrl { get; set; }
    }
}

OnlineshoppingStore.WebUI/Models/PagingInfo.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace OnlineshoppingStore.WebUI.Models
{
    public class PagingInfo
    {
        public int TotalItem { get; set; }
        public int ItemPerPage { get; set; }
        public int CurrentPage { get; set; }
        public int TotalPages
        {
            get
            {

                return (int)Math.Ceiling((decimal)TotalItem / ItemPerPage);

            }


        }
    }
}

OnlineshoppingStore.WebUI/Models/ProductsListViewModel.cs
using OnlineShoppingStore.Domain.Entities;
using System.Collections.Generic;
using System.Web.Mvc;
namespace OnlineshoppingStore.WebUI.Models
{
    public class ProductsListViewModel
    {
        public IEnumerable<Product> Products { get; set; }
        public PagingInfo PagingInfo { get; set; }
        public string CurrentCategory { get; set; }

    }
}

OnlineshoppingStore.WebUI/Controllers/AdminController.cs
using OnlineShoppingStore.Domain.Abstract;
using OnlineShoppingStore.Domain.Entities;
using System.Linq;
using System.Web.Mvc;

namespace OnlineshoppingStore.WebUI.Controllers
{
    public class AdminController : Controller
    {
        private readonly IProductRepository _repo;

        public AdminController(IProductRepository repo)
        {
            _repo = repo;
        }
       
        // GET: Admin
        public ViewResult Index()
        {
            return View(_repo.Products);
        }

        public ViewResult Edit(int productId)
        {
            Product product = _repo.Products.FirstOrDefault(p => p.ProductId == productId);
            return View(product);
        }

        [HttpPost]
        public ActionResult Edit(Product product)
        {
            if (ModelState.IsValid)
            {
                _repo.SaveProduct(product);
                TempData["message"] = string.Format("{0} has been saved", product.Name);
                return RedirectToAction("Index");
            }
            else
            {
            }
            // there is something wrong with the data values
            return View(product);
        }
    }
}

OnlineshoppingStore.WebUI/Controllers/CartsController.cs
using OnlineshoppingStore.WebUI.Models;
using OnlineShoppingStore.Domain.Abstract;
using OnlineShoppingStore.Domain.Entities;
using System.Linq;
using System.Web.Mvc;

namespace OnlineshoppingStore.WebUI.Controllers
{
    public class CartsController : Controller
    {

        private IProductRepository repository;
        private readonly IOrderProcessor _proc;

        public CartsController(IProductRepository repo, IOrderProcessor proc)
        {
            repository = repo;
            _proc = proc;
        }


        public ViewResult Index(Cart cart, string returnUrl)
        {
            return View(new CartIndexViewModel
            {
                Cart = cart,
                ReturnUrl = returnUrl
            });
        }

        public PartialViewResult Summary(Cart cart)
        {
            return PartialView(cart);
        }

        public RedirectToRouteResult AddToCart(Cart cart, int productId, string returnUrl)
        {
            Product product = repository.Products.FirstOrDefault(p => p.ProductId == productId);

            if (product != null)
            {
                cart.AddItem(product, 1);

            }
            return RedirectToAction("Index", new { returnUrl });
        }

        public RedirectToRouteResult RemoveFromCart(Cart cart, int productId, string returnUrl)
        {
            Product product = repository.Products.FirstOrDefault(p => p.ProductId == productId);
            if (product != null)
            {
                cart.RemoveLine(product);
            }
            return RedirectToAction("Index", new { returnUrl });
        }

        public ViewResult Checkout()
        {
            return View(new ShippingDetails());
        }
        [HttpPost]
        public ViewResult Checkout(Cart cart, ShippingDetails shippingDetails)
        {
            if (cart.Lines.Count() == 0)
            {
                ModelState.AddModelError("", "Sorry, your cart is empty!");
            }
            if (ModelState.IsValid)
            {
                _proc.ProcessOrder(cart, shippingDetails);
                cart.Clear();
                return View("Completed");
            }
            else
            {
                return View(shippingDetails);
            }
        }
        /// this was a helper method for shoppping cart
        //private Cart GetCart()
        //{
        //    Cart cart = (Cart)Session["Cart"];
        //    if (cart == null)
        //    {

        //        cart = new Cart();
        //        Session["Cart"] = cart;


        //    }
        //    return cart;
        //}


    }

}

OnlineshoppingStore.WebUI/Controllers/NavController.cs
using OnlineShoppingStore.Domain.Abstract;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace OnlineshoppingStore.WebUI.Controllers
{
    public class NavController : Controller
    {

        private IProductRepository repository;
        public NavController(IProductRepository repo)
        {
            repository = repo;
        }
        // GET: Nav
      public PartialViewResult Menu(string category = null)
        {
            ViewBag.SelectedCategory = category;
            IEnumerable<string> categories = repository.Products
                .Select(x => x.Category)
                .Distinct()
                .OrderBy(x => x);
            return PartialView(categories);

            
        }
    }
}

OnlineshoppingStore.WebUI/Controllers/ProductController.cs
using OnlineshoppingStore.WebUI.Models;
using OnlineShoppingStore.Domain.Abstract;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace OnlineshoppingStore.WebUI.Controllers
{
    public class ProductController : Controller
    {
        // GET: Product
        private readonly IProductRepository repository;
        public int PageSize = 4;
        public ProductController(IProductRepository repo)
        {
            repository = repo;

        }
        public ViewResult List(string category,int page = 1)
        {
            ProductsListViewModel model = new ProductsListViewModel
            {
                Products = repository.Products
                .Where(p => category == null || p.Category == category)
                .OrderBy(p => p.ProductId)
                .Skip((page - 1) * PageSize)
                .Take(PageSize),
                PagingInfo = new PagingInfo
                {
                    CurrentPage = page,
                    ItemPerPage = PageSize,
                    TotalItem = category== null ?
                                repository.Products.Count():
                                repository.Products.Where(p=>p.Category == category).Count()
                },
                CurrentCategory = category
            };


            return View(model);
        }
    }
}

OnlineshoppingStore.WebUI/Views/Admin/Edit.cshtml
@model OnlineShoppingStore.Domain.Entities.Product

@{
    ViewBag.Title = "Admin: Edit " + @Model.Name;
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<div class="panel">
    <div class="panel-heading">
        <h3>Edit @Model.Name</h3>
    </div>
    @using (Html.BeginForm())
    {
        <div class="panel-body">
            @Html.HiddenFor(m => m.ProductId)
            @foreach (var property in ViewData.ModelMetadata.Properties)
            {
                if (property.PropertyName != "ProductId")
                {
                    <div class="form-group">
                        <label>@(property.DisplayName ?? property.PropertyName)</label>
                        @if (property.PropertyName == "Description")
                        {
                            @Html.TextArea(property.PropertyName, null,
new { @class = "form-control", rows = 5 })
                        }
                        else
                        {
                            @Html.TextBox(property.PropertyName, null,
new { @class = "form-control" })
                        }
                    </div>
                }
            }
        </div>
        <div class="panel-footer">
            <input type="submit" value="Save" class="btn btn-primary" />
            @Html.ActionLink("Cancel and return to List", "Index", null, new
{
    @class = "btn btn-default"
})
        </div>
    }
</div>
<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

OnlineshoppingStore.WebUI/Views/Admin/Index.cshtml
@model IEnumerable<OnlineShoppingStore.Domain.Entities.Product>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}




<div class="panel panel-default">
    <div class="panel-heading " style=" height: 40px; margin-top: 10px;" >
        <div>
            All product
        </div>
    </div>
    <div class="panel-body">
        <table  class="table table-striped table-condensed table-bordered table-hover">
            <thead style="color: #000000; background-color: #00fa9a; ">
            <tr>
                <th class="text-right"> ID</th>
                <th>Name</th>
                <th class="text-right">Price</th>
                <th class="text-center">Action</th>
            </tr>
            </thead>
            @foreach (var item in Model)
            {
                <tbody>

                <tr>
                    <td class="table-bordered">@item.ProductId</td>
                    <td>
                        @Html.ActionLink(item.Name, "Edit", new {item.ProductId})
                    </td>
                    <td class="text-right"> @item.Price.ToString("c")</td>
                    <td class="text-center">
                        @using (Html.BeginForm("Delete", "Admin"))
                        {
                            @Html.Hidden("ProductId",item.ProductId)
                            <input type="submit"
                                   class="btn btn-danger btn-xs" value="Delete"/>
                        }
                    </td>
                </tr>
                </tbody>
            }
        </table>

    </div>

    <div class="panel-footer " style="color: #fff0f5;background-color: #008080">

        @Html.ActionLink("Add a New product", "Create",null,new {@class ="btn  btn-default "})
    </div>

</div>

OnlineshoppingStore.WebUI/Views/Carts/Checkout.cshtml
@model OnlineShoppingStore.Domain.Entities.ShippingDetails

@{
    ViewBag.Title = "One stop Mart Shopping :Chckout";


}
<h2>Chck out Now</h2>
<p>Please Enter Your details, and we 'll delivery your goods to your dopr step</p>
@using (Html.BeginForm()) {
    @Html.ValidationSummary()
    <h3>Ship to</h3>
    <div class="form-group">
        <label>Name</label>
        @Html.TextBoxFor(x=>x.Name,new {@class ="form-control"})
        <h3>Address</h3>
        @foreach (var property in ViewData.ModelMetadata.Properties)
        {
            if (property.PropertyName != "Name"&&property.PropertyName !="GiftWrap")
            {
                <div class="form-group">
                    <label>@(property.DisplayName ?? property.PropertyName)</label>
                    @Html.TextBox(property.PropertyName, null,new {@class ="form-control"})

                </div>
            }
        }
        @*<div class="form-group">
            <label>Line 1</label>
            @Html.TextBoxFor(x => x.Line1, new {@class = "form-control"})

        </div>

        <div class="form-group">
            <label>Line 2</label>
            @Html.TextBoxFor(x => x.Line2, new {@class = "form-control"})

        </div>

        <div class="form-group">
            <label>Line 3</label>
            @Html.TextBoxFor(x => x.Line3, new {@class = "form-control"})

        </div>
        <div class="form-group">
            <label>City</label>
            @Html.TextBoxFor(x => x.City, new {@class = "form-control"})

        </div>

        <div class="form-group">
            <label>State</label>
            @Html.TextBoxFor(x => x.State, new { @class = "form-control" })

        </div>

        <div class="form-group">
            <label> Zip</label>
            @Html.TextBoxFor(x => x.Zip, new {@class = "form-control"})

        </div>

        <div class="form-group">
            <label>Country </label>
            @Html.TextBoxFor(x => x.Country, new {@class = "form-control"})

        </div>*@
        <h3>Do you want gift wraper</h3>
        <div class="checkbox">
            <label>@Html.EditorFor(x => x.GiftWrap, new {@class = "form-control"})</label>


        </div>
        <div class="text-center">
            <input class="btn btn-primary" type="submit" value="Complete order"/>
        </div>



    </div>

}

OnlineshoppingStore.WebUI/Views/Carts/Completed.cshtml
@{
    ViewBag.Title = "Completed";
}

<h2>Thank you for patronising I don't tire to waka,.your order will be delivered in a few minute</h2>

OnlineshoppingStore.WebUI/Views/Carts/Index.cshtml
@model OnlineshoppingStore.WebUI.Models.CartIndexViewModel


@{
    ViewBag.Title = "Index";
}

<style>
    #cartTable td{vert-align: middle}
</style>
<h2>Your Cart Items</h2>

<table   class="table table-bordered table-hover">
    <thead style="color: #fff0f5;background-color: #008000">

        <tr>
            <th>Quantity</th>
            <th>Item</th>
            <th>Category</th>

            <th class="text-right">Price</th>
            <th class="text-right">Subtotal</th>
        </tr>
    </thead>
    <hr />
    <tbody>

        @foreach (var line in Model.Cart.Lines)
        {

            <tr>
                <td class="text-center">@line.Quantity</td>
                <td class="text-left">@line.Product.Name</td>
                <td class="text-left">@line.Product.Category</td>

                <td class="text-right">@line.Product.Price.ToString("c")</td>
                <td class="text-right">@((line.Quantity * line.Product.Price).ToString("c"))</td>

                <td>
                    @using (Html.BeginForm("RemoveFromCart", "Carts")) {
                        @Html.Hidden("ProductId",line.Product.ProductId)
                        @Html.HiddenFor(x => x.ReturnUrl);
                        <input class="btn btn-sm btn-warning" type="submit" value="Remove"/>
                    }
                </td>
            </tr>
                    }

    </tbody>
    <tfoot>
        <tr>
            <hr />
            <td colspan="4" class="text-right">Total:</td>
            <td  class="text-right"style="color: red;">@Model.Cart.ComputeTotalValue().ToString("c")</td>

        </tr>
    </tfoot>
</table>
<hr />
<div class="text-center">
    <a class="btn btn-primary" href="@Model.ReturnUrl">Continue shopping</a>
    @Html.ActionLink("Checkout now","Checkout",null,
    new{@class = "btn btn-success"})
</div>

OnlineshoppingStore.WebUI/Views/Carts/Summary.cshtml
@using System.ServiceModel.Configuration
@model OnlineShoppingStore.Domain.Entities.Cart
<div class="navbar-right">
    @Html.ActionLink("Checkout", "Index", "Carts",
        new {returnUrl = Request.Url.PathAndQuery},
        new {@class = "btn btn-success navbar-btn"})

</div>
<div class="navbar-text navbar-right">
    <b>Your Cart has</b>
    @Model.Lines.Sum(x => x.Quantity) item(s),
    @Model.ComputeTotalValue().ToString("c")
</div>

OnlineshoppingStore.WebUI/Views/Nav/Menu.cshtml
@model IEnumerable<string>


@Html.ActionLink("Home","List","Product",null,
    new {@class = "btn btn-block btn-primary btn-lg"})

@foreach (var link in Model)
{

    @Html.RouteLink(
    link, new
{
    controller = "Product",
    action = "List",
    category = link,
    page = 1
},
new {
    @class = "btn btn-block btn-primary btn-lg"
+(link == ViewBag.SelectedCategory? " btn-success":"")


}

    )
}
   

OnlineshoppingStore.WebUI/Views/Product/List.cshtml
@model OnlineshoppingStore.WebUI.Models.ProductsListViewModel

@{
    ViewBag.Title = "Products";
}

@foreach(var p in Model.Products)
{

    @Html.Partial("_ProductSummary", p);
}

<div>
  
    @Html.PageLinks(Model.PagingInfo, x => Url.Action("List", new { page = x,category = Model.CurrentCategory }))
   
    
</div>

OnlineshoppingStore.WebUI/Views/Shared/_AdminLayout.cshtml
@{
    Layout = null;
}
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link href="~/Content/bootstrap-theme.min.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-Flaty.css" rel="stylesheet" />
    <title></title>
</head>
<body>
    <div>
      @if (TempData["message"] != null)
      {
        <div class="alert alert-success">@TempData["message"]</div>
      }
        @RenderBody()
    </div>
</body>
</html>

OnlineshoppingStore.WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - I tire to Waka</title>
    <link href="~/Content/bootstrap-theme.min.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-Flaty.css" rel="stylesheet" />

</head>
<body>
    <div class="container-fluid">

        <div class="navbar navbar-inverse" role="navigation">

            <a class="navbar-brand" href="#">
                <span class="hidden-xs">One Stop Mart</span>
                    <div class="visible-xs">One </div>
                    <div class="visible-xs">Stop</div>
                    <div class="visible-xs">Mart</div>


            </a>
            @Html.Action("Summary", "Carts")
        </div>

        <div class="col-lg-2">
            @Html.Action("Menu", "Nav")
        </div>
        <div class="col-lg-7">

            <div class="panel panel-default">
                <div class="panel-body">
                    <div class="page-header">
                        @RenderBody()


                    </div>

                </div>

            </div>
        </div>
        <div class="col-lg-3">
            <div class=" list-group">
                <a href="#" class="list-group-item active">
                    <h4 class="list-group-item-heading" style="color:white;"> Promotional Package</h4>
                    <hr>
                    <p class="list-group-item-text">
                        Hurray Awuuufff!!! yafuyafu as cyberspace introducte buy one get on free promo
                        this promo valide till end of march
                    </p>
                </a>


                <a href="#" class="list-group-item">
                    <h4 class="list-group-item-heading" style="color:black;">Promotional Package</h4>
                    <hr>
                    <p class="list-group-item-text">
                        Hurray Awuuufff!!! yafuyafu as cyberspace introducte buy one get on free promo
                        this promo valide till end of march
                    </p>
                </a>

                <a href="#" class="list-group-item active">
                    <h4 class="list-group-item-heading" style="color:white;">Promotional Package</h4>
                    <hr>
                    <p class="list-group-item-text">
                        <span class="glyphicon glyphicon-heart"></span> Hurray Awuuufff!!! yafuyafu as cyberspace introducte buy one get on free promo
                        this promo valide till end of march
                    </p>
                </a>

                <a href="#" class="list-group-item">
                    <h4 class="list-group-item-heading" style="color:black;">Promotional Package</h4>
                    <hr>
                    <p class="list-group-item-text">
                        <span class="glyphicon glyphicon-briefcase"></span> Hurray Awuuufff!!! yafuyafu as cyberspace introducte buy one get on free promo
                        this promo valide till end of march
                    </p>
                </a>

                <a href="#" class="list-group-item active">
                    <h4 class="list-group-item-heading" style="color:white;">Promotional Package</h4>
                    <hr>
                    <p class="list-group-item-text">
                        <span class="glyphicon glyphicon-leaf"></span> Hurray Awuuufff!!! yafuyafu as cyberspace introducte buy one get on free promo
                        this promo valide till end of march
                    </p>
                </a>

                <a href="#" class="list-group-item">
                    <h4 class="list-group-item-heading" style="color:black;">Promotional Package</h4>
                    <hr>
                    <p class="list-group-item-text">
                        Hurray Awuuufff!!! yafuyafu as cyberspace introducte buy one get on free promo
                        this promo valide till end of march
                    </p>
                </a>

            </div>
        </div>
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year -fuzzykem</p>
        </footer>
    </div>
    @*<div class="navbar navbar-inverse navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                      <i class="fa fa-bars" aria-hidden="true"></i>
                    </button>
                    @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                    </ul>
                </div>
            </div>
        </div>*@

    <

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>

OnlineshoppingStore.WebUI/Views/Shared/_ProductSummary.cshtml
@model OnlineShoppingStore.Domain.Entities.Product

@{
    ViewBag.Title = "ProductSummary";
}

<h2>ProductSummary</h2>

<div class="well">
    <h3>
        <strong>@Model.Name</strong>
        <span class="pull-right label-primary" style="border-radius:3px;color:white;">@Model.Price.ToString("c")</span>
    </h3>

    @using (Html.BeginForm("AddToCart","Carts"))
    {
        <div class="pull-right">
            @Html.HiddenFor(x => x.ProductId)
            @Html.Hidden("returnUrl", Request.Url.PathAndQuery)
            <input type="submit" class="btn btn-success" value="Add to cart"/>

          
        </div>
    }
    <span class="lead">@Model.Description</span>
</div>